<BoxLayoutWithActionBar>:
    orientation: "vertical"
    ActionBar:
        ActionView:
            ActionPrevious:
                title: root.title
                on_release: app.manager.pop(transition_screen=False)
                padding: "4dp"
                spacing: "4dp"
                app_icon: ""
                previous_image: "images/buttons/home.png"
                previous_image_height: "40dp"
                previous_image_width: "40dp"
